stages:
  - build
  - docker
  - acceptance

## Uncomment the following sections to enable docker, image building and
## acceptance

build:
  stage: build
  image: golang:1.21-alpine3.19
  artifacts:
    paths:
      - bin/
  script:
    - echo Working...
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/car-pooling-challenge cmd/main.go

build_image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo As a helper here you have a sample of how to build and push a \
      docker image to the provided gitlab registry.
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
  dependencies:
      - build
## Uncomment the acceptance step and do not remove or edit, this step is
## required for us to accept your submission!

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address port://pooling:9091 acceptance
